version: '3.7'
services:
  visdom-root-config:
    container_name: visdom-root-config
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - ROOT_BASENAME
    ports:
      - '8500:80'
    restart: always
