# Stage 1: build the application.
FROM node as build-stage
ENV PATH /app/node_modules/.bin:$PATH
WORKDIR /app
COPY package*.json .
RUN npm install
COPY ./ ./
RUN npm run build

# Stage 2, create a production environment.
FROM nginx:stable-alpine
COPY --from=build-stage /app/dist/ /usr/share/nginx/html

# Copy Nginx configuration
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
